# Generated by Django 2.2.4 on 2019-08-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanSpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('spend', models.IntegerField(default=0, verbose_name='مبلغ پیشنهادی')),
                ('mult', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مبلغ پیشنهاد',
                'verbose_name_plural': 'مبلغ پیشنهاد',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'کتگوری',
                'verbose_name_plural': 'کتگوری ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=200, verbose_name='مستعار')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('true_prices', models.IntegerField(default=0, verbose_name='قیمت بازار')),
                ('new_prices', models.IntegerField(default=0, verbose_name='قیمت کف')),
                ('final_prices', models.IntegerField(default=0, verbose_name='قیمت تمام شده')),
                ('precent_price', models.IntegerField(verbose_name='30% قیمت')),
                ('out_of_user', models.BooleanField(default=False, verbose_name='غیرقابل شرکت')),
                ('stack', models.PositiveIntegerField(verbose_name='تعداد')),
                ('available', models.BooleanField(default=True, verbose_name='دردسترس')),
                ('special', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('reset', models.BooleanField(default=False)),
                ('event_start', models.DateTimeField(verbose_name='شروع حراجی')),
                ('event_end', models.DateTimeField(verbose_name='پایان حراجی')),
                ('event', models.BooleanField(default=False, verbose_name='حراجی')),
                ('user_session', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد خرید')),
                ('ended', models.BooleanField(default=False, verbose_name='پایان حراجی')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخت پست')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی پست')),
                ('image', models.ImageField(default='product.jpg', upload_to='')),
                ('image2', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='')),
                ('image3', models.ImageField(blank=True, default='product.jpg', null=True, upload_to='')),
                ('bid_buy', models.ManyToManyField(related_name='products', to='bids.Bid')),
                ('can_spend', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.CanSpend', verbose_name='قیمت پیشنهادی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category', verbose_name='دسته')),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='شرکت کنندگان')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
