# Generated by Django 2.2.4 on 2019-08-21 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190821_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='product', to=settings.AUTH_USER_MODEL, verbose_name='شرکت کنندگان'),
        ),
    ]
