# Generated by Django 2.2.4 on 2019-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190821_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='secret_key',
            field=models.CharField(default='', max_length=200, verbose_name='کد'),
        ),
    ]
