# Generated by Django 2.2.4 on 2019-08-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190822_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precent_price',
            field=models.IntegerField(blank=True, verbose_name='30% قیمت'),
        ),
    ]
