# Generated by Django 2.2.4 on 2019-08-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190822_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cannot_buy',
            field=models.BooleanField(default=False, verbose_name='پایان زمان برای خرید محصول'),
        ),
    ]
