# Generated by Django 2.2.4 on 2019-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_cannot_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reset',
            field=models.BooleanField(default=False, verbose_name='انتخاب دوباره برای حراجی'),
        ),
    ]
