# Generated by Django 2.2.4 on 2019-08-21 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.IntegerField(verbose_name='مبلغ کل پیشنهادی')),
                ('spending', models.IntegerField(default=0, verbose_name='مقدار پیشنهاد داده شده')),
                ('offered', models.SmallIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ساخت این ردیف')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='زمان اخرین بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwinner', to='products.Product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کاربر برنده',
                'verbose_name_plural': 'کاربران برنده شده',
            },
        ),
        migrations.CreateModel(
            name='UserSpend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(blank=True, max_length=200, null=True)),
                ('user_can', models.BooleanField(default=False)),
                ('user_ended', models.BooleanField(default=False)),
                ('email_send', models.BooleanField(default=False)),
                ('user_won', models.BooleanField(default=False)),
                ('new_price', models.IntegerField()),
                ('spending', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 8, 21, 8, 21, 32, 435141, tzinfo=utc))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userspend', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-new_price',),
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد سشن')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان اخرین تغییرات')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سشن کاربر',
                'verbose_name_plural': 'سشن کاربران',
            },
        ),
    ]
