# Generated by Django 2.2.4 on 2019-08-21 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userspends', '0003_auto_20190821_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 10, 45, 12, 929389, tzinfo=utc)),
        ),
    ]
