# Generated by Django 2.2.4 on 2019-08-22 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userspends', '0009_auto_20190822_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 8, 36, 36, 741364, tzinfo=utc)),
        ),
    ]
