# Generated by Django 2.2.4 on 2019-08-24 21:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userspends', '0013_auto_20190822_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 21, 12, 33, 347900, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userwinner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userwinner', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
