# Generated by Django 2.2.4 on 2019-09-08 06:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('userspends', '0015_auto_20190828_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userspend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 8, 6, 26, 30, 486924, tzinfo=utc)),
        ),
    ]
