# Generated by Django 2.2.4 on 2019-08-21 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bids', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='نام خانوادگی')),
                ('bio', models.CharField(blank=True, max_length=500, verbose_name='درباره من')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='شهر')),
                ('address', models.CharField(blank=True, max_length=1000, verbose_name='ادرس')),
                ('phone', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(regex='[0][9][0-9]{9,9}$')], verbose_name='شماره تلفن')),
                ('post_code', models.CharField(blank=True, max_length=20, verbose_name='کدپستی')),
                ('image', models.ImageField(blank=True, default='default.jpg', upload_to='', verbose_name='اواتار')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
        migrations.CreateModel(
            name='BidBoughts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('amount', models.IntegerField(default=0)),
                ('ended', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.Bid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
