# Generated by Django 2.2.4 on 2019-08-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_have_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='have_bid',
            field=models.ManyToManyField(blank=True, related_name='profile', to='accounts.BidBoughts', verbose_name='تعداد بید ها'),
        ),
    ]
