# Generated by Django 2.2.4 on 2019-08-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190821_1305'),
        ('accounts', '0003_auto_20190821_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidboughts',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bidboughts', to='products.Product'),
        ),
    ]
