# Generated by Django 2.2.4 on 2019-08-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bidboughts_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidboughts',
            name='secret_key',
            field=models.CharField(default='', max_length=200, verbose_name='کد'),
        ),
    ]
