# Generated by Django 2.2.4 on 2019-08-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bidboughts_secret_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='have_bid',
        ),
    ]
