# Generated by Django 2.2.4 on 2019-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190821_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidboughts',
            options={'verbose_name': 'بید خریداری شده', 'verbose_name_plural': 'بیدهای خریداری شده'},
        ),
    ]
