# Generated by Django 2.2.4 on 2019-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190828_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.PositiveIntegerField(default=0, verbose_name='کیف پول'),
        ),
    ]
