# Generated by Django 2.2.4 on 2019-08-21 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(blank=True, max_length=200, null=True, verbose_name='کد سشن')),
                ('user_can', models.BooleanField(default=False, verbose_name='توان خرید')),
                ('user_ended', models.BooleanField(default=False, verbose_name='خریداری کرده/نکرده')),
                ('user_won', models.BooleanField(default=False, verbose_name='برنده شده/نشده')),
                ('email_send', models.BooleanField(default=False, verbose_name='ایمیل فرستاده شده/نشده')),
                ('new_price', models.IntegerField(verbose_name='مبلغ کل پیشنهادی')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='تعداد پیشنهادات داده شده')),
                ('spending', models.IntegerField(default=0, verbose_name='مقدار پیشنهادات داده شده')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='زمان اخرین بروزرسانی')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 8, 21, 8, 21, 17, 24443, tzinfo=utc), verbose_name='اتمام زمان توان خرید')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend', to='products.Product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت کننده',
                'verbose_name_plural': 'شرکت کنندگان',
            },
        ),
    ]
