# Generated by Django 2.2.4 on 2019-08-21 14:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0007_auto_20190821_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='true_price',
            field=models.IntegerField(default=0, verbose_name='قیمت خرید'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 14, 5, 40, 53470, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
