# Generated by Django 2.2.4 on 2019-08-21 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0008_auto_20190821_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 21, 21, 32, 58, 324993, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
