# Generated by Django 2.2.4 on 2019-08-22 08:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0012_auto_20190822_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 8, 46, 46, 309184, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
