# Generated by Django 2.2.4 on 2019-08-24 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0013_auto_20190822_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 24, 21, 12, 33, 345905, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
