# Generated by Django 2.2.4 on 2019-08-27 13:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0014_auto_20190825_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='def_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 13, 2, 19, 947618, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
