# Generated by Django 2.2.4 on 2019-08-30 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0016_auto_20190828_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='spend',
            name='status',
            field=models.CharField(blank=True, choices=[('winner', 'برنده'), ('looser', 'بازنده'), ('transferred', 'جایگاه واگذار شده')], max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 15, 4, 39, 174308, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
    ]
