# Generated by Django 2.2.4 on 2019-11-15 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spendations', '0019_auto_20190908_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spend',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 15, 15, 34, 7, 83997, tzinfo=utc), verbose_name='اتمام زمان توان خرید'),
        ),
        migrations.AlterField(
            model_name='spend',
            name='last_spend',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 15, 15, 34, 7, 83997, tzinfo=utc), verbose_name='زمان اخرین پیشنهاد'),
        ),
    ]
