# Generated by Django 2.2.4 on 2019-08-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='نام')),
                ('slug', models.SlugField(verbose_name='نام نوار ادرس')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='تعداد')),
                ('stack', models.PositiveIntegerField(verbose_name=' تعداد موجودی')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, default='bid.jpg', upload_to='', verbose_name='تصویر')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ساخت پست')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی پست')),
            ],
        ),
    ]
