# Generated by Django 2.2.4 on 2019-08-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_remove_bid_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='secret_key',
            field=models.CharField(default='', max_length=200, verbose_name='کد'),
        ),
    ]
