# Generated by Django 2.2.4 on 2019-08-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_bid_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='secret_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='کد'),
        ),
    ]
