# Generated by Django 2.2.4 on 2019-08-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20190822_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'بید', 'verbose_name_plural': 'بید ها'},
        ),
    ]
