# Generated by Django 2.2.4 on 2019-08-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_auto_20190828_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='rank',
            field=models.CharField(choices=[('gold', 'طلایی'), ('silver', 'نقره ای'), ('bronze', 'برنز')], default='gold', max_length=20, verbose_name='نوع بید'),
        ),
    ]
