# Generated by Django 2.2.4 on 2019-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_bid_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='rank',
            field=models.CharField(choices=[('gold', 'طلایی'), ('silver', 'نقره ای'), ('bronze', 'برنزی')], default='gold', max_length=20, verbose_name='نوع بید'),
        ),
    ]
