# Generated by Django 2.2.4 on 2019-08-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'ساخته شده'), ('canceled', 'کنسل شده'), ('paid', 'پرداخت شده')], default='created', max_length=20, verbose_name='وضعیت'),
        ),
    ]
